from typing import TypedDict, Annotated, List
import operator

# This is the "Memory" of our agent.
# In a production system, this state is what gets saved to the database.
class AgentState(TypedDict):
    # The stock ticker the user asked about (e.g., "AAPL")
    ticker: str
    
    # A list of messages between the user, the agent, and the tools.
    # We use Annotated + operator.add so that new messages get appended 
    # to the list rather than overwriting it.
    messages: Annotated[List[dict], operator.add]
    
    # Any financial data we fetch gets stored here temporarily
    financial_data: dict
    
    # The final research report generated by the AI
    final_report: str
